Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.synced_folder "./data", "/instance_data"
  config.vm.synced_folder "../data", "/global_data"
  
  config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "4096"
  end
  

  config.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install -y apache2
      a2enmod rewrite
      cp -f /instance_data/apache2.conf /etc/apache2/apache2.conf


      apt install -y mysql-server
      apt install -y zip
      apt install -y php
      apt install -y openjdk-8-jdk
      apt install -y apt-transport-https
      apt-get install -y sendmail

      cp /global_data/composer.phar /usr/local/bin/composer
      mkdir -p /var/www/html/php
      cp -r /instance_data/phpinfo.php /var/www/html/php/index.php 
      rm -rf /tmp/phpMyAdmin-5.0.4-all-languages.zip /tmp/phpMyAdmin-5.0.4-all-languages
      wget --quiet -O /tmp/phpMyAdmin-5.0.4-all-languages.zip https://files.phpmyadmin.net/phpMyAdmin/5.0.4/phpMyAdmin-5.0.4-all-languages.zip
      unzip /tmp/phpMyAdmin-5.0.4-all-languages.zip -d /tmp/
      rm -rf /var/www/html/phpMyAdmin
      mv /tmp/phpMyAdmin-5.0.4-all-languages /var/www/html/phpMyAdmin
      cp -r /instance_data/config.inc.php /var/www/html/phpMyAdmin/config.inc.php 

      echo "Installation PHP extensions."
      add-apt-repository -y ppa:ondrej/php
      apt update
      apt install -y php7.4-fpm 
      apt install -y php7.4-common 
      apt install -y php7.4-mysql 
      apt install -y php7.4-gmp 
      apt install -y php7.4-curl 
      apt install -y php7.4-intl 
      apt install -y php7.4-mbstring 
      apt install -y php7.4-xmlrpc 
      apt install -y php7.4-gd 
      apt install -y php7.4-xml 
      apt install -y php7.4-cli 
      apt install -y php7.4-zip 
      apt install -y php7.4-bcmath
      apt install -y php7.4-soap
      cp /instance_data/php.ini /etc/php/7.4/fpm/php.ini

      mysql -u root < /instance_data/create_magento_database.sql

      wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
      echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
      apt update
      apt install -y elasticsearch
     
      systemctl daemon-reload
      systemctl enable elasticsearch.service
      systemctl start elasticsearch.service

      echo "Restarting services"
      systemctl restart apache2
      systemctl restart mysql
      systemctl restart php7.4-fpm

      systemctl status apache2
      systemctl status mysql
      systemctl status php7.4-fpm
   SHELL

end
